# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='database.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64\x61tabase.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n\x06Symbol\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"*\n\nSymbolPair\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1c\n\x08RowCount\x12\x10\n\x08rowcount\x18\x01 \x01(\r\":\n\x14TrendWithDefaultDate\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x12\n\npopularity\x18\x02 \x01(\r\"Z\n\x0c\x42oughtOrSold\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12(\n\x04\x64\x61te\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x32\xbf\x03\n\x08\x44\x61tabase\x12\x33\n\nGetSymbols\x12\x16.google.protobuf.Empty\x1a\x0b.SymbolPair0\x01\x12!\n\tGetSymbol\x12\x07.Symbol\x1a\x0b.SymbolPair\x12)\n\rUpsertSymbols\x12\x0b.SymbolPair\x1a\t.RowCount(\x01\x12\x32\n\x0eInsertPttTrend\x12\x15.TrendWithDefaultDate\x1a\t.RowCount\x12\x36\n\x12InsertReunionTrend\x12\x15.TrendWithDefaultDate\x1a\t.RowCount\x12\x30\n\x14InsertTwseOverBought\x12\r.BoughtOrSold\x1a\t.RowCount\x12.\n\x12InsertTwseOverSold\x12\r.BoughtOrSold\x1a\t.RowCount\x12\x31\n\x15InsertFugleOverBought\x12\r.BoughtOrSold\x1a\t.RowCount\x12/\n\x13InsertFugleOverSold\x12\r.BoughtOrSold\x1a\t.RowCountb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SYMBOL = _descriptor.Descriptor(
  name='Symbol',
  full_name='Symbol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='Symbol.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=104,
)


_SYMBOLPAIR = _descriptor.Descriptor(
  name='SymbolPair',
  full_name='SymbolPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='SymbolPair.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='SymbolPair.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=148,
)


_ROWCOUNT = _descriptor.Descriptor(
  name='RowCount',
  full_name='RowCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rowcount', full_name='RowCount.rowcount', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=178,
)


_TRENDWITHDEFAULTDATE = _descriptor.Descriptor(
  name='TrendWithDefaultDate',
  full_name='TrendWithDefaultDate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='TrendWithDefaultDate.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='popularity', full_name='TrendWithDefaultDate.popularity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=238,
)


_BOUGHTORSOLD = _descriptor.Descriptor(
  name='BoughtOrSold',
  full_name='BoughtOrSold',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='BoughtOrSold.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='BoughtOrSold.date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='BoughtOrSold.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=330,
)

_BOUGHTORSOLD.fields_by_name['date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Symbol'] = _SYMBOL
DESCRIPTOR.message_types_by_name['SymbolPair'] = _SYMBOLPAIR
DESCRIPTOR.message_types_by_name['RowCount'] = _ROWCOUNT
DESCRIPTOR.message_types_by_name['TrendWithDefaultDate'] = _TRENDWITHDEFAULTDATE
DESCRIPTOR.message_types_by_name['BoughtOrSold'] = _BOUGHTORSOLD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Symbol = _reflection.GeneratedProtocolMessageType('Symbol', (_message.Message,), {
  'DESCRIPTOR' : _SYMBOL,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:Symbol)
  })
_sym_db.RegisterMessage(Symbol)

SymbolPair = _reflection.GeneratedProtocolMessageType('SymbolPair', (_message.Message,), {
  'DESCRIPTOR' : _SYMBOLPAIR,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:SymbolPair)
  })
_sym_db.RegisterMessage(SymbolPair)

RowCount = _reflection.GeneratedProtocolMessageType('RowCount', (_message.Message,), {
  'DESCRIPTOR' : _ROWCOUNT,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:RowCount)
  })
_sym_db.RegisterMessage(RowCount)

TrendWithDefaultDate = _reflection.GeneratedProtocolMessageType('TrendWithDefaultDate', (_message.Message,), {
  'DESCRIPTOR' : _TRENDWITHDEFAULTDATE,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:TrendWithDefaultDate)
  })
_sym_db.RegisterMessage(TrendWithDefaultDate)

BoughtOrSold = _reflection.GeneratedProtocolMessageType('BoughtOrSold', (_message.Message,), {
  'DESCRIPTOR' : _BOUGHTORSOLD,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:BoughtOrSold)
  })
_sym_db.RegisterMessage(BoughtOrSold)



_DATABASE = _descriptor.ServiceDescriptor(
  name='Database',
  full_name='Database',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=333,
  serialized_end=780,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSymbols',
    full_name='Database.GetSymbols',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SYMBOLPAIR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSymbol',
    full_name='Database.GetSymbol',
    index=1,
    containing_service=None,
    input_type=_SYMBOL,
    output_type=_SYMBOLPAIR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpsertSymbols',
    full_name='Database.UpsertSymbols',
    index=2,
    containing_service=None,
    input_type=_SYMBOLPAIR,
    output_type=_ROWCOUNT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InsertPttTrend',
    full_name='Database.InsertPttTrend',
    index=3,
    containing_service=None,
    input_type=_TRENDWITHDEFAULTDATE,
    output_type=_ROWCOUNT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InsertReunionTrend',
    full_name='Database.InsertReunionTrend',
    index=4,
    containing_service=None,
    input_type=_TRENDWITHDEFAULTDATE,
    output_type=_ROWCOUNT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InsertTwseOverBought',
    full_name='Database.InsertTwseOverBought',
    index=5,
    containing_service=None,
    input_type=_BOUGHTORSOLD,
    output_type=_ROWCOUNT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InsertTwseOverSold',
    full_name='Database.InsertTwseOverSold',
    index=6,
    containing_service=None,
    input_type=_BOUGHTORSOLD,
    output_type=_ROWCOUNT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InsertFugleOverBought',
    full_name='Database.InsertFugleOverBought',
    index=7,
    containing_service=None,
    input_type=_BOUGHTORSOLD,
    output_type=_ROWCOUNT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InsertFugleOverSold',
    full_name='Database.InsertFugleOverSold',
    index=8,
    containing_service=None,
    input_type=_BOUGHTORSOLD,
    output_type=_ROWCOUNT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATABASE)

DESCRIPTOR.services_by_name['Database'] = _DATABASE

# @@protoc_insertion_point(module_scope)
